// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjO83FDg5XEm3dfszJrmqX-FTsLcKT3Aw',
    appId: '1:938450509812:web:38341339807682b42ba3a1',
    messagingSenderId: '938450509812',
    projectId: 'shoprite-608e0',
    authDomain: 'shoprite-608e0.firebaseapp.com',
    storageBucket: 'shoprite-608e0.firebasestorage.app',
    measurementId: 'G-D0TEVB6ZNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDFE94a4Ffi9JVGSW8iw_9c_H16lFIy4',
    appId: '1:938450509812:android:1eda64c96e0393182ba3a1',
    messagingSenderId: '938450509812',
    projectId: 'shoprite-608e0',
    storageBucket: 'shoprite-608e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-eWGI2cNCy3x2cTWBzjuNXgvbF_qiqs',
    appId: '1:938450509812:ios:c96bc5424f1bd99e2ba3a1',
    messagingSenderId: '938450509812',
    projectId: 'shoprite-608e0',
    storageBucket: 'shoprite-608e0.firebasestorage.app',
    iosBundleId: 'com.example.shopRiteEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-eWGI2cNCy3x2cTWBzjuNXgvbF_qiqs',
    appId: '1:938450509812:ios:c96bc5424f1bd99e2ba3a1',
    messagingSenderId: '938450509812',
    projectId: 'shoprite-608e0',
    storageBucket: 'shoprite-608e0.firebasestorage.app',
    iosBundleId: 'com.example.shopRiteEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjO83FDg5XEm3dfszJrmqX-FTsLcKT3Aw',
    appId: '1:938450509812:web:695829a344f33bb62ba3a1',
    messagingSenderId: '938450509812',
    projectId: 'shoprite-608e0',
    authDomain: 'shoprite-608e0.firebaseapp.com',
    storageBucket: 'shoprite-608e0.firebasestorage.app',
    measurementId: 'G-L48JT71YGT',
  );
}
